export const ADICIONAR_PROJETO = 'ADICIONAR_PROJETO';
export const EDITAR_PROJETO = 'EDITAR_PROJETO';
export const REMOVER_PROJETO = 'REMOVER_PROJETO';
export const ADICIONAR_NOTIFICACAO = 'ADICIONAR_NOTIFICACAO';